dist: bionic
language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  - sudo apt-get install info install-info libturbojpeg0-dev
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
  - cl -e '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)'

script:
  - cl -f $TRAVIS_BUILD_DIR/tests/travis.lisp
